import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import AOSInitializer from "../components/AOSInitializer";

import Script from "next/script";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Zayra Dental",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <AOSInitializer />

        <main>
          <div
            style={{
              background: "linear-gradient(135deg,rgb(240, 13, 232), #f28dff)",
              width: "100vw",
              height: "100vh",
              position: "fixed",
              left: 0,
              zIndex: -1,
            }}
          ></div>
          {children}
        </main>
        <Footer />

      </body>
    </html>
  );
}
